{% set name = "ecape-parcel" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ecape_parcel-{{ version }}.tar.gz
  sha256: c6a1050fa4717dce77113721977ba707451c675cc9efddaf04fb32ea3ed139a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - ecape
    - metpy
    - numpy
    - pint

test:
  imports:
    - ecape_parcel
  commands:
    - pip check
  requires:
    - python {{ python_min }}

about:
  summary: A simple Python package that computes entrainment CAPE parcels.
  dev_url: https://github.com/a-urq/ecape-parcel-py
  home: https://github.com/a-urq/ecape-parcel-py
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
